AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: mysql
      EngineVersion: 5.7
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: !Ref DBMasterUserPassword
      DBInstanceIdentifier: my-mysql-instance
      PubliclyAccessible: true
      DBName: MyDatabase

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet group for RDS instance"
      SubnetIds:
        - subnet-0bb1c79de3EXAMPLE
        - subnet-064cd4c5acEXAMPLE

Parameters:
  DBMasterUsername:
    Type: String
    NoEcho: true
    Description: "The database admin account username"
  DBMasterUserPassword:
    Type: String
    NoEcho: true
    Description: "The database admin account password"