AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyDBSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: "Allow access to MySQL"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '3306'
          ToPort: '3306'
          CidrIp: '0.0.0.0/0'

  MyRDSInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: 'my-mysql-instance'
      AllocatedStorage: '20'
      DBInstanceClass: 'db.t2.micro'
      Engine: 'mysql'
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      VPCSecurityGroups:
        - !GetAtt MyDBSecurityGroup.GroupId
      BackupRetentionPeriod: 0
      PubliclyAccessible: true
      DBName: 'testdb'

Parameters:
  MasterUsername:
    Type: String
    Description: "The master username for the RDS instance"
    Default: "admin"

  MasterUserPassword:
    Type: String
    Description: "The master user password for the RDS instance"